Should CSS Naked Day last 50 hours?
css-naked-day/css-naked-day.github.io pull request #95
Opened 2023-04-14 15:36 UTC by chrisburnell

Hello there!

In doing some reading off the back of CSS Naked Day this year, I learned of two UTC offsets that I didn't expect: **UTC+13** and **UTC+14**.

In the spirit of allowing ourselves to be caught with our pants down to **everyone** on April 9 of every year, does this mean that our international day should last **50 hours** instead of **48 hours**? e.g.

from:
`YYYY-04-09-00:00:00+1400`

until:
`YYYY-04-09-23:59:59-1200` / `YYYY-04-10-00:00:00-1200`

---

Apologies in advance if this change isn't applicable.

Many thanks!

2023-04-16 17:09 UTC, arkhi commented
Hello @chrisburnell!

Time is amazing; thanks for pointing this out.

This change would also imply contacting developers of the [scripts and plugins](https://css-naked-day.github.io/#tools) out there.

I’ll check this further next week.

2023-04-19 11:40 UTC, arkhi requested changes
Hello. :)

Beside the rewording for the id and fragment identifier, I’m all good for the change.
Maybe something like `timespan` instead of the number?

Thanks!

2023-04-19 11:40 UTC, arkhi commented on index.html
> +          <h3 id="forty-height"><a id="fifty" href="#fifty">Wait… isn’t that 50 hours?</a></h3>
Thanks for saving the previous fragment!

We could benefit of a fragment that is not based on a numerical value here. Imagine there are other changes… :)

2023-04-19 11:48 UTC, chrisburnell commented on index.html
> +          <h3 id="forty-height"><a id="fifty" href="#fifty">Wait… isn’t that 50 hours?</a></h3>
Just pushed [03e498c](https://github.com/css-naked-day/css-naked-day.github.io/pull/95/commits/03e498c038b093572e32332dca146022bbdf6f0b) which makes this change.

Hopefully it’s what you’re looking for!

2023-04-19 11:49 UTC, arkhi commented on index.html
> +          <h3 id="forty-height"><a id="fifty" href="#fifty">Wait… isn’t that 50 hours?</a></h3>
Lovely. Thanks. :)

2023-04-19 11:50 UTC, arkhi approved these changes

2023-04-19 11:50 UTC, merged

2023-04-19 12:05 UTC, arkhi commented
Pinging @ajalapus, @retohugi, @sgerrand, @jefftriplett, @designerbrent, @danielsellergren, in case you’d like to update your [scripts](https://css-naked-day.github.io/#tools) (if needed).